/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define DIM 5

struct Input {
	char a;
	int b;
};
typedef struct Input Input;

struct Output {
	char a[DIM];
};
typedef struct Output Output;

#define PROGRAM 0x20000013
#define PROGRAMVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FUNZIONE_UNO 1
extern  int * funzione_uno_1(Input *, CLIENT *);
extern  int * funzione_uno_1_svc(Input *, struct svc_req *);
#define FUNZIONE_DUE 2
extern  Output * funzione_due_1(Input *, CLIENT *);
extern  Output * funzione_due_1_svc(Input *, struct svc_req *);
extern int program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FUNZIONE_UNO 1
extern  int * funzione_uno_1();
extern  int * funzione_uno_1_svc();
#define FUNZIONE_DUE 2
extern  Output * funzione_due_1();
extern  Output * funzione_due_1_svc();
extern int program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Input (XDR *, Input*);
extern  bool_t xdr_Output (XDR *, Output*);

#else /* K&R C */
extern bool_t xdr_Input ();
extern bool_t xdr_Output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
